---
- name: Test playbook
  hosts: localhost 
  tasks:

    - name: Sending an e-mail using Gmail SMTP servers
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: fakeemail@gmail.com
        password: fakepassword
        to: Josh Henson <jdh0986@gmail.com>
        subject: Ansible-report
        body: This will probably fail to work.
      delegate_to: localhost
